"""init-db

Revision ID: 5d65b18b3104
Revises: ee3bf2bdadf5
Create Date: 2023-10-31 16:39:37.446845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d65b18b3104'
down_revision: Union[str, None] = 'ee3bf2bdadf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centros_treinamento',
    sa.Column('pk_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('endereco', sa.String(length=60), nullable=False),
    sa.Column('proprietario', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('pk_id'),
    sa.UniqueConstraint('nome')
    )
    op.drop_table('centros_treinamentos')
    op.drop_constraint('atletas_centro_treinamento_id_fkey', 'atletas', type_='foreignkey')
    op.create_foreign_key(None, 'atletas', 'centros_treinamento', ['centro_treinamento_id'], ['pk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'atletas', type_='foreignkey')
    op.create_foreign_key('atletas_centro_treinamento_id_fkey', 'atletas', 'centros_treinamentos', ['centro_treinamento_id'], ['pk_id'])
    op.create_table('centros_treinamentos',
    sa.Column('pk_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('endereco', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('proprietario', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('pk_id', name='centros_treinamentos_pkey'),
    sa.UniqueConstraint('nome', name='centros_treinamentos_nome_key')
    )
    op.drop_table('centros_treinamento')
    # ### end Alembic commands ###
